apiVersion: apps/v1
kind: Deployment
metadata:
  name: cowsay
  labels:
    app: cowsay
spec:
  selector:
    matchLabels:
      app: cowsay
  replicas: 2
  template:
    metadata:
      labels:
        app: cowsay
    spec:
      containers:
        - name: cowsay
          image: ukko/cowsay:0.7
          ports:
            - containerPort: 80
              protocol: TCP
        - name: redis
          image: redis
          ports:
            - containerPort: 3679
