apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: cowsay-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
    - http:
        paths:
          - path: /cowsay
            backend:
              serviceName: cowsay-service
              servicePort: 80